/* ACCIONES AL CARGAR UN NUEVO NEGOCIO */
export const NEW_TURNO = "NEW_TURNO";
export const SET_LOGIN = "SET_LOGIN";
export const SWITCH_MENU = "SWITCH_MENU";
export const EDIT_PACIENTE = "EDIT_PACIENTE";
export const EDIT_SERVICIO = "EDIT_SERVICIO";
export const EDIT_DOCTOR = "EDIT_DOCTOR";
export const EDIT_PROGRAMAR = "EDIT_PROGRAMAR";
export const EDIT_HORARIO = "EDIT_HORARIO";
export const EDIT_FECHA = "EDIT_FECHA";
export const FECHA_AGENDA = "FECHA_AGENDA";
export const EDIT_ALL = "EDIT_ALL";
export const BORRAR_TURNO = "BORRAR_TURNO";
export const EDIT_NOTA = "EDIT_NOTA";
export const EDIT_TIPO_SERVICIO = "EDIT_TIPO_SERVICIO";
export const EDIT_CD_TURNO = "EDIT_CD_TURNO";
export const SET_DEFAULT = "SET_DEFAULT";
export const SET_USUARIO = "SET_USUARIO";
export const SET_LISTA_USUARIOS = "SET_LISTA_USUARIOS";
export const SELECT_DIA_MES = "SELECT_DIA_MES";
export const VISTAMENSUALSEMANAL = "VISTAMENSUALSEMANAL";

export const SET_OBRA_SOCIAL = "SET_OBRA_SOCIAL";
export const SET_LISTA_OBRA_SOCIAL = "SET_LISTA_OBRA_SOCIAL";
export const SET_PLAN = "SET_PLAN";
export const SET_LISTA_PLANES = "SET_LISTA_PLANES";

export const SET_ESPECIALIDAD = "SET_ESPECIALIDAD";
export const SET_LISTA_ESPECIALIDAD = "SET_LISTA_ESPECIALIDAD";

export const SET_SERVICIO = "SET_SERVICIO";
export const SET_LISTA_SERVICIOS = "SET_LISTA_SERVICIOS";

export const SET_PRESTADORA = "SET_PRESTADORA";
export const SET_LISTA_PRESTADORA = "SET_LISTA_PRESTADORA";

export const SET_TIPO_SERVICIO = "SET_TIPO_SERVICIO";
export const SET_LISTA_TIPO_SERVICIO = "SET_LISTA_TIPO_SERVICIO";

export const SET_COSTO_SERVICIO = "SET_COSTO_SERVICIO";
export const SET_LISTA_COSTO_SERVICIO = "SET_LISTA_COSTO_SERVICIO";

export const SET_PROFESIONAL = "SET_PROFESIONAL";
export const SET_LISTA_PROFESIONAL = "SET_LISTA_PROFESIONAL";

export const SET_PACIENTE = "SET_PACIENTE";
export const SET_LISTA_PACIENTE = "SET_LISTA_PACIENTE";

export const SET_HORARIOS = "SET_HORARIOS";

export const SET_TURNOS = "SET_TURNOS";
export const SELECT_PROFESIONAL = "SELECT_PROFESIONAL";

export const SET_HISTORIA_CLINICA = "SET_HISTORIA_CLINICA";
export const SET_LISTA_HISTORIA_CLINICA = "SET_LISTA_HISTORIA_CLINICA";

export const SET_TURNOS_VISTA_MENSUAL = "SET_TURNOS_VISTA_MENSUAL";
export const SET_TURNOS_VISTA_SEMANAL = "SET_TURNOS_VISTA_SEMANAL";

export const BUSCAR_TURNOS = "BUSCAR_TURNOS";

export const SET_TIPO = "SET_TIPO";
export const SET_REPETIR = "SET_REPETIR";
export const SET_CANTIDAD = "SET_CANTIDAD";
export const SET_ARRAY_DIAS = "SET_ARRAY_DIAS";
export const SET_DIA = "SET_DIA";
export const CLEAN_PROGRAMAR = "CLEAN_PROGRAMAR";

export const CLEAN_GLOBAL = "CLEAN_GLOBAL";
export const BUSCAR_PACIENTE = "BUSCAR_PACIENTE";
export const BUSCAR_PROFESIONAL = "BUSCAR_PROFESIONAL";
export const BUSCAR_ACTUALES = "BUSCAR_ACTUALES";
export const MODAL_HISTORIA_CLINICA = "MODAL_HISTORIA_CLINICA";
export const ERROR_MESSAGE = "ERROR_MESSAGE";

export const SET_LISTA_PERFIL = "SET_LISTA_PERFIL";
export const SET_PERFIL = "SET_PERFIL";

export const CLEAN_BUSCAR_TURNOS = "CLEAN_BUSCAR_TURNOS";
